"""Public API for the :mod:`ECLlib` package."""

# Version-number generated by setuptools_scm from git tags.
# Do not edit this file manually, it will be overwritten by the build process.
# To update the version, create a new git tag with the format vX.Y.Z (e.g., v1.0.0).
# setuptools_scm will automatically detect this tag and set the version accordingly.
from ._version import version as __version__

from .core import File, RefreshIterator, Restart
from .input import DATA_file
from .output import (
    EGRID_file,
    FUNRST_file,
    INIT_file,
    MSG_file,
    PRTX_file,
    PRT_file,
    RFT_file,
    RSM_block,
    RSM_file,
    SMSPEC_file,
    UNRST_file,
    UNSMRY_file,
    fmt_block,
    fmt_file,
    text_file,
)
from .intersect import AFI_file, IXF_file, IX_input
from .unformatted import unfmt_block, unfmt_file
from .File_checker import File_checker
from .gsgfile import change_resolution, read_GSG, write_GSG
from .constants import ENDSOL

__all__ = [
    "__version__",
    "File",
    "DATA_file",
    "EGRID_file",
    "INIT_file",
    "UNRST_file",
    "RFT_file",
    "UNSMRY_file",
    "SMSPEC_file",
    "text_file",
    "MSG_file",
    "PRT_file",
    "PRTX_file",
    "fmt_block",
    "fmt_file",
    "FUNRST_file",
    "RSM_block",
    "RSM_file",
    "AFI_file",
    "IXF_file",
    "IX_input",
    "unfmt_file",
    "Restart",
    "unfmt_block",
    "RefreshIterator",
    "File_checker",
    "read_GSG",
    "write_GSG",
    "change_resolution",
    "ENDSOL",
]
