"""Public API for the :mod:`ECLlib` package."""

# Version-number generated by setuptools_scm from git tags.
# Do not edit this file manually, it will be overwritten by the build process.
# To update the version, create a new git tag with the format vX.Y.Z (e.g., v1.0.0).
# setuptools_scm will automatically detect this tag and set the version accordingly.
from ._version import version as __version__

from .core import File, AutoRefreshIterator, Restart
from .io.input.eclipse import DATA_file
from .io.input.gsgfile import (
    PROP_data, read_prop_file, write_prop_file, change_resolution, read_GSG, write_GSG
)
from .io.input.intersect import AFI_file, IXF_file, IX_input

from .io.output import (
    EGRID_file, FUNRST_file, INIT_file, MSG_file, PRTX_file, PRT_file, 
    RFT_file, RSM_block, RSM_file, SMSPEC_file, UNRST_file, UNSMRY_file,
    NameIndexedValues, KeyIndexedValues, RSSPEC_file, fmt_block, fmt_file, text_file,
)
from .io.unformatted.base import ENDSOL, unfmt_block, unfmt_file
from .io.output.file_checker import File_checker

__all__ = [
    "__version__",
    "File", "AutoRefreshIterator", "Restart",
    "DATA_file",
    "PROP_data", "read_prop_file", "write_prop_file", "change_resolution", "read_GSG", "write_GSG",
    "AFI_file", "IXF_file", "IX_input",
    "EGRID_file", "FUNRST_file", "INIT_file", "MSG_file", "PRTX_file", "PRT_file",
    "RFT_file", "RSM_block", "RSM_file", "SMSPEC_file", "UNRST_file", "UNSMRY_file",
    "NameIndexedValues", "KeyIndexedValues", "RSSPEC_file", "fmt_block", "fmt_file", "text_file",
    "ENDSOL", "unfmt_file", "unfmt_block",
    "File_checker",
]
